### ISSUE TITLE
Lire une ligne du fichier correction dans le script evaluer-tp2.sh

### ISSUE THREAD

**Issue by BousqueE** [guyfrancoeur/INF3135_E2019_TP#10]
Salut ! C'est normal que ```for line in `cat inf3135-e2019-tp1.correction`; do echo $line; done``` affiche un seul mot par ligne, délimité par des espaces ? Je m'attendais à afficher les lignes du fichier avec cette commande, puisque le script `evaluer-tp2.sh` indique que la variable est `line`...  Voici une partie de ce qui s'affiche quand j'entre la commande (Je remarque aussi que "-e" ne s'affiche pas) :
0
00
0
make
(default:)
grep
-c

'default
:'

'default:'
Makefile

StackExchange semble recommander d'utiliser la forme `while read line; do echo "$line"; done < inf3135-e2019-tp1.correction`, mais je ne crois pas que ce soit possible, puisque le modèle pour `evaluer-tp2.sh` ne semble permettre d'ajout que dans la boucle `for`...

**Comment by lesGrandsBras** [comment]
Je pense qu'il faut que tu découpes la ligne pour aller chercher juste ce qui t'intéresse et ensuite que tu trouves une commande qui te permettra d'exécuter la portion découpée .

**Comment by LauriGui** [comment]
Salut @BousqueE,

Une petites recherche d’informations sur la variable `IFS` devrait t’aider à comprendre le pourquoi de ce problème ;)

**Comment by BousqueE** [comment]
> Salut @BousqueE,
> 
> Une petites recherche d’informations sur la variable `IFS` devrait t’aider à comprendre le pourquoi de ce problème ;)

En effet, ça fonctionne en dehors de la boucle `for` (Et par le fait même, en dehors de la section `#votre code ici` ), mais je n'arrive pas obtenir le même résultat en assignant une valeur à IFS à l'intérieur de la boucle `for`. Est-ce qu'on peut modifier le script au-delà de la section `#votre code ici`?

**Comment by LauriGui** [comment]
Oui, tant que la structure générale reste là :)

**Comment by alexchaoss** [comment]
> > Salut @BousqueE,
> > Une petites recherche d’informations sur la variable `IFS` devrait t’aider à comprendre le pourquoi de ce problème ;)
> 
> En effet, ça fonctionne en dehors de la boucle `for` (Et par le fait même, en dehors de la section `#votre code ici` ), mais je n'arrive pas obtenir le même résultat en assignant une valeur à IFS à l'intérieur de la boucle `for`. Est-ce qu'on peut modifier le script au-delà de la section `#votre code ici`?

Je crois pas que c'est possible de redéfinir le IFS à l'intérieur de la boucle si tu l'as déjà fait en dehors de la boucle. Le mieux serait de te faire une fonction et de le changer à l'intérieur de cette fonction.
