### ISSUE TITLE
Fichier dictionnaire

### ISSUE THREAD

**Issue by MichaelCapone** [guyfrancoeur/INF3135_E2019_TP#11]
Bonjour,

dans l'éventualité que le répertoire passé en argument à l'option ''-l'' soit invalide, est-il préférable de lancer l'erreur avec le code de sortie 9 ou bien de se faire notre propre code d'erreur (+11). Cette question découle du fait que pour le tp1, chaque erreur de lecture de fichier possèdait son code d'erreur. Merci et bon courage à tous !

Michael

**Comment by fpblondin** [comment]
Personnellement, si aucun répertoire n'est passé en paramètre après -l j'ai mis un code 9 mais si le répertoire n'est pas accessible ou inexistant j'ai mis un code  11+
