### ISSUE TITLE
Le fichier inf3135-e2019-tp1.correction n'est pas 100% compatible pour le tp2, que dois-je faire ?

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_E2019_TP#13]
Bonjour,

Premierement, merci à tout ceux qui posent les questions dans les `ISSUES`, bravo.

Un petit retour, désolé,
Le fichier de correction du tp1 corrige les fonctionnalités du tp1.

Il est souhaitable de construire un nouveau fichier `correction` similaire à celui du tp1 pour valider et tester votre tp2.
Il est de plus fort possible que certaines commandes doivent être mise à jour afin de valider les requis du tp2.

Qu'en pensez-vous ?

**Comment by lesGrandsBras** [comment]
Vous parlez d'un fichier de correction que vous allez faire (c'est sûr qu'il y en aura un) ou que nous devrions faire pour faire nos tests à nous et laisser dans notre dépôt?
Je ne suis pas sûre de comprendre votre question!

**Comment by injailoutsoon** [comment]
Bonjour, je vois une maj dans le script(vieille m'ai je viens de m'en apercevoir maintenant)
permettez moi juste de vous faire remarquuer qu'il y'a un "THEN" qui manque ici

if [ ! -f ${correction} ]
  wget -q https://github.com/guyfrancoeur/INF3135_E2019_TP/raw/master/${correction} -O ${correction}
f

**Comment by fpblondin** [comment]
Oui l'ancienne version a mangé mon fichier passé en paramètres (wget écrasait les fichiers) :-/

**Comment by guyfrancoeur** [comment]
Bonjour,

Effectivement, un then était manquant dans le template.

Merci à celui et ceux qui a corrigé l'erreur et continué leur tp.
