### ISSUE TITLE
Fihier dictionnaire-espagnol

### ISSUE THREAD

**Issue by injailoutsoon** [guyfrancoeur/INF3135_E2019_TP#14]
Bonjour,

je m’aperçois que l' "es" est maintenant barré dans l’énoncé; j'en déduis que juste 3 dictionnaires de valides maintenant. Voulez vous confirmez SVP ?

Merci

**Comment by guyfrancoeur** [comment]
Bonjour,

Vous n'avez pas à gérer l'espagnol.

Merci

**Comment by MaxNicol** [comment]
Si mon programme gère déjà le module en espagnol. Dois-je enlever la fonctionnalité?
