### ISSUE TITLE
structure.h/structure.c

### ISSUE THREAD

**Issue by alexchaoss** [guyfrancoeur/INF3135_E2019_TP#15]
Dans l'énoncé il est écrit qu'on peut avoir plusieurs TAD.

Si on en utilise plusieurs est-ce qu'on doit les mettres tous dans le même fichier (structure.c/structure.h)?

**Comment by fpblondin** [comment]
En théorie tes TDA doivent être dans structure.h et les fonctions qui leurs sont associées dans structure.c

**Comment by guyfrancoeur** [comment]
Bonjour,

Q. Est-ce possible d'avoir plusieurs TAD dans le meme fichier ?
Q. Voyez-vous un problème ou un enjeu avec plusieurs TAD dans même fichier ?

Pour des raisons de simplicité (compilation surtout) `structure.h` et `structure.c` devraient être utilisés.
Il est souhaitable que si des fichiers additionnels soient **absolument** requis vous devez m'avisez.

Commentez!
