### ISSUE TITLE
Est-ce que des fichiers dans modèle sont créés dans le système de Windows? 

### ISSUE THREAD

**Issue by Xuquanzhang** [guyfrancoeur/INF3135_E2019_TP#16]

**Comment by MaxNicol** [comment]
Selon l'énoncé du tp2, tous les fichiers doivent être au format Unix. J'imagine donc que la meme chose s'applique pour les fichiers utilisés en correction.

**Comment by MaxNicol** [comment]
Non, les fichiers sont au format Unix!
