### ISSUE TITLE
Nom des fichiers de langues

### ISSUE THREAD

**Issue by fredalas** [guyfrancoeur/INF3135_E2019_TP#18]
Est-il nécéssaire d'implementer une portion de code qui liste l'ensemble des noms de fichiers dans le répertoire de langue?

Si l'on considere que les fichiers utilisés lors de la correction seront exactement les mêmes que ceux fournis, alors il serait possible de valider seulement le nom du repo fourni en ligne de commande.

**Comment by fpblondin** [comment]
Les noms des fichiers pourraient changer.  Le programme doit fonctionner pour tous les fichiers avec des extensions .fr .en et .de

**Comment by guyfrancoeur** [comment]
Bonjour,

Les noms ainsi que le contenu pourrait changer.
