### ISSUE TITLE
Cas d'un bruteforce sans succès

### ISSUE THREAD

**Issue by MichaelCapone** [guyfrancoeur/INF3135_E2019_TP#20]
Bonjour à tous,

cette question concerne le cas où un bruteforce donnerais 0% pour toutes les clefs d'encryptation. Si cette situation se produit, est-ce préférable de lancer un code d'erreur (11+) ou bien de tout simplement mettre sur la sortie le même message recu. Merci et bonne perséverance à tous !

Michael

**Comment by guyfrancoeur** [comment]
Allo, 

Mettre un code d'erreur 10 idealement ou 11+...

Merci pour la question.
