### ISSUE TITLE
Précision sur le output du script evaluer-tp2.sh

### ISSUE THREAD

**Issue by MichaelCapone** [guyfrancoeur/INF3135_E2019_TP#21]
Bonjour à tous,

Question #1: 
L'avant dernière ligne du output du script est la suivante:

"Note (total) pour FRAG12345678 dans inf3135-e2019-tp2: 11"

Est-ce que "inf3135-e2019-tp2" correspond au nom du fichier de correction utilisé pour l'exécution du script sans l'extension ou bien est-ce hardcodé ? J'opte bien sur pour le premier choix mais j'ai quand même un léger doute ;) 

Question #2:
Un test qui échoue à cause d'un timeout, est-ce qu'on l'indique ou bien on conserve le même affichage, c'est-à-dire "echoue".

Merci à tous !

Michael

**Comment by guyfrancoeur** [comment]
Allo,

Réponse no1:
Je crois que j'avais utilisé une variable. Mais a vous de voir comment vous désirez le faire.  Je ne suis pas contre les deux méthodes.

Réponse no2:
Un échec est un échec. Peu importe la raison.

Merci pour les questions.

**Comment by guyfrancoeur** [comment]
``
