### ISSUE TITLE
Formatage du fichier correction pour le script.

### ISSUE THREAD

**Issue by MichaelCapone** [guyfrancoeur/INF3135_E2019_TP#22]
Bonjour,

j'aimerais savoir si nous avions convenu d'un formatage spécial pour le fichier de correction en classe. La méthode que j'utilise en ce moment fonctionne très bien mais dépend du fait que la dernière colonne soit précédée de 4 espaces.

Serait-il donc possible de confirmer le standard du formatage pour que l'on puisse être sur que la fonc dont on extrait les informations nécessaires de chaque ligne fonctionnera également avec le fichier de correction qui sera utilisé ultérieurement ?

Merci !

Michael

**Comment by iFredOS** [comment]
Ça semble totalement standard et constant dans le fichier de .correction. Pour moi ça semble évident qu’il utilisera le même format pour ce TP. Les espaces sont fixes entre les colonnes.

Frédéric

**Comment by MichaelCapone** [comment]
Bonjour Fred,

merci de ta réponse. Les espaces sont bel et et bien fixes pour les premieres colonnes mais cependant ils ne le sont pas entre les deux dernières colonnes. Pour saisir la dernière colonne, je me sert du fait qu'il semble avoir au moins un minimum de 4 espaces entre les deux dernières colonnes mais si cela venait à changer, mon script ne fonctionnairait pas.

Un de mes amis m'a dit que la colonne de la commande commence a la 29 ième position et selon lui, ce serait le professeur qui aurait dit cela en classe mais je ne m'en souviens absolument pas. Merci !

Michael

**Comment by iFredOS** [comment]
> Un de mes amis m'a dit que la colonne de la commande commence a la 29 ième position et selon lui, ce serait le professeur qui aurait dit cela en classe mais je ne m'en souviens absolument pas. Merci !

C’est ce que je voulais écrire, mais je ne sais ce qu’on peut écrire ou pas ici. Donc, tu as presque la réponse. Fait juste compter de nouveau. 😉

**Comment by MichaelCapone** [comment]
Merci ! HAHAHA, car mon premier réflexe lorsque je parse un fichier ce n'est pas de compter les colonnes mais plutot de chercher les délimiteurs.

**Comment by iFredOS** [comment]
> Merci ! HAHAHA, car mon premier réflexe lorsque je parse un fichier ce n'est pas de compter les colonnes mais plutot de chercher les délimiteurs.

Je pense exactement comme toi. Il a fallu que je change mon approche pour ce fichier. 🤓

**Comment by guyfrancoeur** [comment]
Allo,

Colonnes sont fixes.

Donc vous pouvez les compter.  Le format ne changera pas.

Merci.
