### ISSUE TITLE
Précision sur utilisation de l’option -l

### ISSUE THREAD

**Issue by LouisMp** [guyfrancoeur/INF3135_E2019_TP#23]
S’il y a plusieurs fichiers `.fr` (par exemple) dans le dossier donné dans l’option `-l` ils faut que les mots qu’ils contiennent soient tous dans le même dico (l’instance de structure) ?

**Comment by MichaelCapone** [comment]
Bonjour Louis,

cela dépend bien sur de comment tu décide de faire ton programme. Ce qui est sur, c'est que si on a 9 fichiers de dictionnaire (avec des extensions valides) dans le répertoire contenant chacun 100 mots, tu auras à vérifier 900 mots. Ta structure va te permettre de contenir aisément tes données (les mots) et de les traiter (d'où le terme de type de données abstraite). Maintenant, demande-toi, comme si tu code en JAVA, qu'elle est la différence entre avoir 9 arraylists de 100 mots chaucune ou bien une arraylist contenant les 900 mots... j'espère que cela est une bonne piste de réflexion pour toi !

PS: Je te rappelle que Guy ne demande pas à ce qu'on fasse une distinction quelconque entre les 3 langues.

Bon courage, 

Michael

**Comment by BenoitCarignan** [comment]
Bonjour monsieur Capone,

Effectivement, Guy ne demande pas de faire la distinction entre les langues. 
Par contre, si le fichier contient des mots de plusieurs langues.... Par exemple, 30% de français, 30% d'anglais et 40% d'allemand. 
Si les deux premières langues sont encodées avec la même clef et que la troisième est encodée avec un autre clef, les résultats pourraient être différents si on considère les dictionnaires comme un tout au-lieu de les considérer un par un.

**Comment by MichaelCapone** [comment]
Bonjour M. Carignan,

il me semble que M. Guyfrancoeur a dit en classe que le fichier à décoder contiendra seulement des mots d'une même langue.

Michael

**Comment by MichaelCapone** [comment]
De plus, je ne comprends pas ce que vous voulez dire lorsque vous dites ''Si les deux premières langues sont encodées avec la même clef et que la troisième est encodée avec un autre cle''... non seulement le fichier sera d'une seule langue mais aussi la totalité de celui-ci sera encodé avec la même clef. Ainsi, a moins que mon cerveau ne me fasse defaut, le fait de traiter les dictionnaires dans leur ensemble ou bien de facon séparé de par leur langue ne pose aucune différence algorithmiquement. Selon moi, le fait que l'on n'est pas a distinguer entre les langues engendre alors le fait que l'on n'est pas a maintenir de statistique du nombre de mot trouvé dans chaque dictionnaire. Cependant, je peux me tromper... ;) 

Michael

**Comment by LouisMp** [comment]
Je ne pense pas que vous ayez compris la question, je demandes si dépendamment des fichiers contenu dans le dossier modele est-ce que par ex 3 dictionnaires francais seront crees s'il y a 3 fichiers  `.fr` ?

**Comment by MichaelCapone** [comment]
> 
> 
> Je ne pense pas que vous ayez compris la question, je demandes si dépendamment des fichiers contenu dans le dossier modele est-ce que par ex 3 dictionnaires francais seront crees s'il y a 3 fichiers `.fr` ?

Oui, tous les fichiers ayant une extension valide (.rf, .en, .es) sont pris. Si il y en a 23 avec une extension .fr, alors tu prends les 23 ! 

Bon courage, 

Michael
