### ISSUE TITLE
Fichiers corrections tp1

### ISSUE THREAD

**Issue by LouisMp** [guyfrancoeur/INF3135_E2019_TP#24]
Bonjour, les colonnes du fichiers corrections sont séparées par un `TAB` ou par un `SPACE` ?

**Comment by berserk64** [comment]
Bonjour, après avoir fait l'analyse du charactère ascii dans le inf3135-e2019-tp1.correction de l'espace entre les colonnes, cela semble bien être un SPACE (soit la valeur 32 sur la table ASCII) entre ceux-ci.
Bonne continuation!

**Comment by iFredOS** [comment]
> Edit: En fait, il semblerait bien qu'il y ait des tabulation entre les 2 dernière colonne. ( Rappel une tabulation equivaux à 4 espace)
**Faux**. `TAB` (␉ | symbol for horizontal tabulation) à la valeur ASCII = 9 ou UNICODE = U+2409. La tabulation n’a aucune équivalence en nombre d’espace, car chaque personne (programmeur) peut lui donner la valeur qui lui plait. C'est une mauvaise perception de penser que 4 fois le caractère `SPACE` espaces équivaut à `TAB`, car ce n'est pas du tout la même chose.

**Comment by berserk64** [comment]
Ah d'accord je te remercie pour l'éclaircissement! Mon temps passé à écrire sur des éditeurs de texte ma induit en erreur en ce qui concerne la programmation et le caractère ASCII. L'espacement de 4 devait donc être un paramètre par défaut lorsqu'on pèse sur la touche  `TAB` sur ces éditeurs de textes. Je m'excuse grandement pour mon mauvais raisonnement!

**Comment by LouisMp** [comment]
Donc les colonnes sont séparées d’un ´\t´ ou pas ?

**Comment by MichaelCapone** [comment]
> 
> 
> Donc les colonnes sont séparées d’un `\t` ou pas ?

Il semble avoir eu un consensus au dernier cours (dont je n'ai aucun souvenir...) qu'une certaine colonne qui commence à une certaine position commencera toujours à cette même position. Pour faire un parralèle avec la fonction printf, c'est comme si chaque colonne avait un nombre d'espace qui lui était prédeterminé.

Michael

**Comment by guyfrancoeur** [comment]
Allo,

ni des tab ni des esapces

Le fichier est fixe (position) 

col 1; position 0 (len 1) : points
col 2; position 2-3 (len 2) : temps
col 3; position 5 (len 1) : code de retour 

etc...

**Comment by MichaelCapone** [comment]
Bonjour 

> 
> 
> Allo,
> 
> ni des tab ni des esapces
> 
> Le fichier est fixe (position)
> 
> col 1; position 0 (len 1) : points
> col 2; position 2-3 (len 2) : temps
> col 3; position 5 (len 1) : code de retour
> 
> etc...

Bonjour M. Francoeur,

juste pour clarifier et éviter les ambiguités, la colonne #3 pour le code de retour commence à la position 5 (si on compte à partir de 0 comme dans pour les tableaux) mais je crois que la longueur devrait être de 2 plutot que 1 étant donné que maintenant, pour le tp2, nous avons des codes de retour plus grand que 9. Merci !

Michael

**Comment by LauriGui** [comment]
Salut @MichaelCapone,

Tu peux faire ça, pour un fichier de tests personnels, mais le standard, pour la correction devrait rester le même, car les codes d’erreurs qui sont vraiment évalués (dont on peut être sûr de la valeur exacte) sont inférieurs à 10... Si on veut tester qu’un code d’erreur supérieur à 10 a été ajouté, pour une situation quelconque, on pourrait par exemple rajouter un test qui permettrait de valider ce cas!

**Comment by jaimenday** [comment]
Merci pour la réponse concernant les les positions des colonnes. Est-ce qu'on peut avoir une présentation des résultats selon nous tant qu'on a les bons résultats au total des points?

**Comment by MichaelCapone** [comment]
> 
> 
> Merci pour la réponse concernant les les positions des colonnes. Est-ce qu'on peut avoir une présentation des résultats selon nous tant qu'on a les bons résultats au total des points?

Non, l'énoncé dit de faire un effort pour avoir un affichage aussi proche que possible que celui dans l'exemple ! Tu es capable !

Michael

**Comment by jaimenday** [comment]
Merci Mic! Je suis capable !
