### ISSUE TITLE
Script Bash commande make introuvable

### ISSUE THREAD

**Issue by LouisMp** [guyfrancoeur/INF3135_E2019_TP#25]
Bonjour, 
Lorsque mon script essaie de lancer la commande il est dit qu'elle est introuvable est-ce que quelqu'un d'autre a eu ce problème ? J'ai cherché sur internet et on me demande de faire un `sudo apt-get install --reinstall make` mais j'ai pas les autorisations. J'utilise PuTTy sur windows 10 mon script marcherais sans ça est-ce qu'il est livrable ?

**Comment by LouisMp** [comment]
Pas que la commande make d'autres commandes aussi comme ls grep diff

**Comment by alexchaoss** [comment]
Ça m'était arrivé au début, je n'utilisais pas la bonne façon dans mon script pour lancer mes commandes.
