### ISSUE TITLE
Question sur la valeur de retour.

### ISSUE THREAD

**Issue by JingxingTu** [guyfrancoeur/INF3135_E2019_TP#27]
Quand l'argument **-d** et **-e** ne sont pas présents,mais **-b** est présent.
Dans ce cas,est-ce qu'il toujours retourne 4. La même question pour l'a
rgument **-k**, s'il n'est pas présent, mais **-b** est présent, ça retourne 7?

**Comment by LauriGui** [comment]
Salut @JingxingTu,

Si `-b` est présent, alors `-d` et/ou `-e` ne sont pas nécessaires, mêmes qu’ils ne doivent pas être présents... Ensuite, si `-k` et `-b` sont utilisés ensemble, c’est une erreur d’utilisation. Selon moi, le code de retour 9 serait celui correspondant le mieux à la situation... ;)

**Comment by JingxingTu** [comment]
Dans l'énoncé, il y a des exigences si-desous:

> 4 : l'argument -d ou -e n'est pas présent;
> 7 : l'argument -k n'est pas présent, ou la valeur passée n'est pas conforme;

S'il y a l'argument -b ,c'est quoi la valeur de retour , 0 , 4 ,7 ,9?

**Comment by LauriGui** [comment]
Logiquement, si on réfléchit aux rôles de chaque argument, si `-b` remplace `-d`/`-e`, le fait que l’un des deux ne soit pas présent ne me semble plus une erreur non...? 
Et comme @guyfrancoeur l’a déjà dit (et c’est peut-être même dans l’énoncé), si on repère des nouveaux codes d’erreurs, on peut les ajouter (11+), il faut les gérer. 

La partie de l’énoncé que tu as cité n’a pas changé du tp1... Il faut ajuster en fonction des nouvelles contraintes! (Ex: 4: l’argument -d ou -e n’est pas présent; (s’il est nécessaire, pour le cas qui est évalué) comme pour les codes 5 et 6, on en tient compte seulement s’ils sont nécessaires au bon fonctionnement/s’ils sont à inclure dans la validation des arguments)

**Comment by guyfrancoeur** [comment]
Bonjour,

Les deux cas (utilisation des options) suivants sont distincts :
+ -b et -l  (obligatoire)
+ -d | -e et -k (obligatoire)

+ -a, -i, -o sont des options facultatives utilisées avec cas précédents.

Cordialement,
