### ISSUE TITLE
Question sur script evaluer-tp2.sh

### ISSUE THREAD

**Issue by lesGrandsBras** [guyfrancoeur/INF3135_E2019_TP#3]
Allo!

Je ne comprends pas la première ligne de code du script:
```if [ -z $1 ]```
c'est quoi ce `-z`?

Merci d'avance!

*Edit: Note @guyfrancoeur , je ne vois pas où je peux ajouter un label à ma question, j'ai fait le test sur mon propre dépôt, je pense qu'on doit être propriétaire pour pouvoir mettre des 'labels'!*

**Comment by LauriGui** [comment]
Salut @lesGrandsBras,

Je suis sûr que tu peux trouver la réponse à ta question, dans les notes du prof ;)

Non, en effet, tu ne peux pas ajouter de `labels`...

**Comment by lesGrandsBras** [comment]
Oui , j'ai trouvé merci :)
