### ISSUE TITLE
make test / make data

### ISSUE THREAD

**Issue by vurten** [guyfrancoeur/INF3135_E2019_TP#32]
Bonjour j'aimerais savoir s'il y a un nouveau lien pour le make data et make test pour le tp2 ou bien on doit juste laisser ce qu'on a fait pour le tp1 dans notre Makefile? Merci.

**Comment by KladRos** [comment]
On doit juste laisser ou corriger ce qui a déjà été fait pour le tp1.

Selon la description du travail dans la section ''Makefile'' :
''Les cibles du TP1 et TP2 doivent être corrigé seulement, aucun ajout de fonctionnalité dans une cible existante;''
et
''
data:
        #ici comme dans le tp1

test:
        #ici comme dans le tp1

resultat:
        #ici comme dans le tp1
''

Donc je doute que le lien est à changer.

**Comment by vurten** [comment]
merci @KladRos pour réponse
