### ISSUE TITLE
Laisser le traitement des arguments dans main.c.

### ISSUE THREAD

**Issue by capitainemuffin** [guyfrancoeur/INF3135_E2019_TP#34]
Allo tout le monde,

Est-ce acceptable de laisser la fonction de traitement des arguments dans le fichier `main.c`?

Dans mon cas, à chaque nouvel argument lu, quelque chose se passe dans unes de mes TDA. Je ne peux donc pas mettre la fonction dans `outils.c`, car celle-ci deviendrait dépendante de `structures.c`.

Je ne sais pas si c'est courant ou si je devais changer la façon de procéder.

Merci !

**Comment by guyfrancoeur** [comment]
À ce point ci,

Il est préférable de viser un résultat efficace.
Ne changez pas trop ce qui fonctionne bien.

Évitez les dépendances inter-librairies.

Donc, je ne suis pas contre une gestion et un remplisage de votre TAD à partir du main().

Cordialement,
