### ISSUE TITLE
Est-ce que cela sera grave que j'ai oublié à ajouter 's' dans le nom des fichier outils.c et outils.h?

### ISSUE THREAD

**Issue by Xuquanzhang** [guyfrancoeur/INF3135_E2019_TP#38]

**Comment by JingxingTu** [comment]
Même question!! J'ai écrit "outil.s", ce sera 0?

**Comment by MichaelCapone** [comment]
Bonsoir,

ne paniquez pas ! M. Francoeur a grand coeur, ce ne sera certainement pas 0 ! Si ce l'est, ce sera au plus pour un seul test seulement (donc 1 point sur 25). Tant que votre `make` fonctionne et que vous compilez avec les noms de fichiers que vous avez ecrit par erreur, les tests vont fonctionner quand même. Allez profiter du reste de l'été car l'hivers arrive bientot ! Bonne vacance !

Michael

**Comment by guyfrancoeur** [comment]
Bonjour,

svp faire les corrections rapidement.

Je vais faire un clone (global) à `07h59 ET`

Cordialement,

**Comment by JingxingTu** [comment]
@guyfrancoeur  Je viens de corriger, merci!

**Comment by Xuquanzhang** [comment]
Merci, merci beaucoup.
