### ISSUE TITLE
Précision code de retour # 9: Les options obligatoires ne sont pas toutes présentes ou mal utilisées

### ISSUE THREAD

**Issue by fpblondin** [guyfrancoeur/INF3135_E2019_TP#4]
Considérant que s'il n'y a aucun argument ou que `–c ` n'est pas présent c'est le code `0`, que si `–d` ou `–e` n'est pas présent c'est le code `4`, que si `–k` n'est pas présent c'est le code `7`.

Peut-on prendre pour acquis que le code `9` va s'appliquer uniquement à `–b` avec `–l`?

**Comment by fpblondin** [comment]
Je vois que le code `9` s'applique maintenant aux arguments mal utilisés.
La présence d'un même argument 2 fois (`-d` `-d` ou `-k 5` `-k 8`) ou la présence simultanée de `-e` `-d` arrêtent maintenant le programme en étant considérés comme mal utilisés plutôt que de prendre le dernier soumis?

**Comment by LauriGui** [comment]
Salut, ton premier message est un peut abstrait... mais pour le deuxième, en reprenant ton exemple de -e suivie de -d, c’est vrai, mais ça pourrait tout aussi être -e -k 3 -d... dès qu’il y a une mauvaise utilisation des arguments ;)
