### ISSUE TITLE
Output script evaluer-tp2.sh

### ISSUE THREAD

**Issue by fpblondin** [guyfrancoeur/INF3135_E2019_TP#5]
Est-ce que le output du script de test `evaluer-tp2.sh` est affiché sur la sortie standard ou envoyé dans un fichier? Si c'est dans un fichier doit-il avoir un nom particulier (ex: `resultat.tp2`)?

**Comment by guyfrancoeur** [comment]
Allo,

Bonne demande de précision, merci.

La sortie standard est la réponse.
