### ISSUE TITLE
inf3135-e2019-tp1.correction vs tp2

### ISSUE THREAD

**Issue by fpblondin** [guyfrancoeur/INF3135_E2019_TP#6]
Le script `inf3135-e2019-tp1.correction` évalue le tp1.  Est-ce que le script qu'on appelle avec `evaluer-tp2.sh` ne devrait pas plutôt s'appeler `inf3135-e2019-tp2.correction` et évaluer toutes ces commandes avec le tp2 plutôt que le tp1? C'est un oubli ou c'est voulu et c'est à nous de changer la commande tp1 pour tp2 à l'intérieur lorsqu'on l'appelle?

**Comment by LauriGui** [comment]
Salut @fpblondin,

C’est vrai que ça peut être mélangeant, mais les noms sont bons, on créer un script, pour le tp2 (c’est de là que vient le nom) et le fichier de correction est celui du tp1 qu’on peut utiliser, pour vérifier que les contraintes du tp1 sont biens gérées, mais comme on peut le deviner, pour tester les contraintes supplémentaires qui s’ajoutent au tp2, ce ne sera pas suffisant donc si on change le nom pour `inf3135-e2019-tp2.correction`, ça pourrait laisser croire que ce l’est...
