### ISSUE TITLE
librairie dirent.h

### ISSUE THREAD

**Issue by fpblondin** [guyfrancoeur/INF3135_E2019_TP#7]
Est-ce que l'utilisation de la librairie `dirent.h` est permise?

**Comment by guyfrancoeur** [comment]
Bonjour,

Cette librairie est disponible dans avec le compilateur GCC, Linux et le serveur java.labunix.uqam.ca.

Ceci dit `dirent.h` n'est pas standard.  Si vous croyez que cette librairie est utile pour vous, je ne suis pas contre. Est-ce la façon la plus facile de faire?

Il serait parcontre important de savoir ce quelle contient.
