### ISSUE TITLE
Un alphabet est une chaîne de caractères ascii ?

### ISSUE THREAD

**Issue by suolson** [guyfrancoeur/INF3135_E2019_TP#8]
Bonjour, est-ce que vous voulez dire : au lieu que l'alphabet soit 26 lettres comme avant, c'est plutôt toutes les caractères de la table ascii imprimables entre la valeur décimale : [33-126] qu'on va utiliser pour décaler ?

Merci, 
Suol

**Comment by LauriGui** [comment]
Salut @suolson,

Pour le TP1, ainsi que pour le 2ème, on dit « l'alphabet » tout simplement, pour représenter le fichier `alphabet.txt` (son contenu n'était pas forcément les 26 lettres de l'alphabet français...) Donc, c'est comme si on « réinventait » l'alphabet... Tous les caractères de la tables ASCII peuvent en faire partie! « ASCII » est précisé, afin qu'on puisse être sur que tout caractère n'en faisant pas partie, n'aura pas à être géré... (Ex: un emoji... 😜)
